import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AppSettingsProvider } from "@/context/AppSettingsContext";
import SideNav from "@/components/globals/SideNav/SideNavComponent";
import TopNav from "@/components/globals/TopNav/TopNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bauplan UI Concept",
  description: "Generated by create next app",
  icons: {
    icon: "/bauplan-logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-br from-zinc-900 to-slate-800`}>
        <AppSettingsProvider>
          <div className="flex w-full h-screen">
            <SideNav />
            <div className="flex flex-1 flex-col overflow-auto">
              <TopNav />
              <div className="flex-1 overflow-auto p-8">
                {children}
              </div>
            </div>
          </div>
        </AppSettingsProvider>
      </body>
    </html>
  );
}
